services:
  postgres:
    image: postgres:16-alpine
    container_name: seminuevos_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: seminuevos_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - seminuevos_pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d seminuevos_db"]
      interval: 5s
      timeout: 5s
      retries: 10
  #  pgadmin:
  #    image: dpage/pgadmin4:latest
  #    restart: always
  #    environment:
  #      - PGADMIN_DEFAULT_EMAIL=admin@admin.com  # Correo ficticio para iniciar sesión
  #      - PGADMIN_DEFAULT_PASSWORD=admin         # Contraseña para iniciar sesión
  #    ports:
  #      - "5050:80" # <-- Puerto para entrar desde el navegador
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"

volumes:
  seminuevos_pgdata:
